% ReadinessSignal: MATLAB technical computing lane stays dependency-light.
ReadinessSignal = struct( ...
  "lane", "matlab", ...
  "status", "reference", ...
  "score", 141, ...
  "reducedMotionSafe", true, ...
  "runtimeWeight", "dependency-light" ...
);
