// Generated by scripts/create-convex-queries.mjs from apps/fullstack/state-model.json.
// Do not edit by hand. Regenerate with: npm run automation:convex-queries
//
// Deferred source: compiles after `npx convex dev` codegen at backend
// provisioning. Reads are owner-only via Convex Auth once provisioned
// (docs/decisions/auth-jwt-decision-record.md).
import { query } from "./_generated/server";

// Installed Codex plugins with lane assignment and policy compliance.
export const listPluginRegistry = query({
  args: {},
  handler: async (ctx) => await ctx.db.query("plugin_registry").collect(),
});

// Operational lanes grouping plugins by build surface.
export const listPluginLanes = query({
  args: {},
  handler: async (ctx) => await ctx.db.query("plugin_lanes").collect(),
});

// Canonical repository state and consolidated source repositories.
export const listRepositories = query({
  args: {},
  handler: async (ctx) => await ctx.db.query("repositories").collect(),
});

// Full-history source refs preserved inside SEIS.
export const listSourceBranches = query({
  args: {},
  handler: async (ctx) => await ctx.db.query("source_branches").collect(),
});

// Google Workspace operating artifacts linked into SEIS.
export const listWorkspaceLinks = query({
  args: {},
  handler: async (ctx) => await ctx.db.query("workspace_links").collect(),
});

// Operating gates the cockpit footer renders.
export const listGovernanceGates = query({
  args: {},
  handler: async (ctx) => await ctx.db.query("governance_gates").collect(),
});
