// Generated by scripts/create-convex-schema.mjs from apps/fullstack/state-model.json.
// Do not edit by hand. Regenerate with: npm run automation:convex-schema
//
// Deferred source: requires `convex` (installed at backend provisioning per
// docs/decisions/backend-state-decision-record.md). The static cockpit keeps
// working unchanged until the live backend is provisioned.
import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  // Installed Codex plugins with lane assignment and policy compliance.
  plugin_registry: defineTable({
    plugin_id: v.string(),
    lane_id: v.string(),
    channel: v.string(),
    installed: v.boolean(),
    policy_compliant: v.boolean(),
  }),

  // Operational lanes grouping plugins by build surface.
  plugin_lanes: defineTable({
    lane_id: v.string(),
    label: v.string(),
    active_count: v.number(),
    missing_count: v.number(),
  }),

  // Canonical repository state and consolidated source repositories.
  repositories: defineTable({
    repository: v.string(),
    role: v.string(),
    default_branch: v.string(),
    snapshot_path: v.union(v.string(), v.null()),
    history_preserved: v.boolean(),
    archive_ready: v.boolean(),
  }),

  // Full-history source refs preserved inside SEIS.
  source_branches: defineTable({
    ref: v.string(),
    origin_repository: v.string(),
    origin_branch: v.string(),
    verified: v.boolean(),
  }),

  // Google Workspace operating artifacts linked into SEIS.
  workspace_links: defineTable({
    link_id: v.string(),
    kind: v.string(),
    title: v.string(),
    url: v.string(),
    recurrence: v.union(v.string(), v.null()),
  }),

  // Operating gates the cockpit footer renders.
  governance_gates: defineTable({
    gate_id: v.string(),
    label: v.string(),
    state: v.string(),
  }),
});
